### PR TITLE
Fixed: grid doesn't refresh when _gridOptions.data is an empty array

### PR DESCRIPTION
**Pull request by RickZee**
Hi,

Please see a fix that would make the grid refresh when you assign empty array to gridOptions.data

Cheers,
Rick

### CODE REVIEW

**Comment by RickZee** [comment]
Hi @AlexanderZhukCoherent, would you please let me know when you'll have some time to review this? We'd like to start using the fixed component on our project.

**Comment by AlexanderZhukCoherent** [comment]
@RickZee Will do by this Friday. At a first glance, your change makes sense, though the condition 'newValue.length > -1' will always be 'true' for any array or string, regardless of the newValue, so it can be eliminated in this case. Will re-review and let you know in the next 3 days, thanks.

**Comment by RickZee** [comment]
Sounds great! Thanks much @AlexanderZhukCoherent

The idea with 'newValue.length > -1' is to also account for the empty array. In that case newValue.length is '0' which is a falsy value but we want to refresh the grid nevertheless. Hopefully this helps. Please let me know if I can help in any way :)

Thanks,
Rick.

**Comment by AlexanderZhukCoherent** [comment]
fixed in c87e29dee019f2e45ec793033ec11df1eab21a72

**Pull request closed without merging**
